apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-enterprise-config
  namespace: quay-enterprise
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
