---
# tasks file for clair

# Not needed as we deploy on quay
#- name: Add SCC anyuid to default account
#  shell: "oc adm policy add-scc-to-user anyuid -z default -n clair"

- name: Create Clair Postgres
  openshift_raw:
    src: "{{ role_path }}/files/{{item}}"
  with_items:
  - clair-postgresql-volume.yml
  - clair-postgresql-deployment.yml
  - clair-postgresql-service.yml

- name: Create Clair App Objects
  openshift_raw:
    src: "{{ role_path }}/files/{{item}}"
  with_items:
  - clair-cm.yml
  - clair-deployment.yml
  - clair-service.yaml
