---
# tasks file for clair

# Create Project
- name: Create Clair project
  openshift_v1_project:
    name: clair

- name: Add SCC anyuid to default account
  shell: "oc adm policy add-scc-to-user anyuid -z default -n clair"

- name: Create Clair ConfigMap
  k8s_v1_config_map:
    src: "{{ role_path }}/files/configmap.yml"
    namespace: clair

- name: Create Clair Service
  k8s_v1_service:
    src: "{{ role_path }}/files/service.yml"
    namespace: clair

- name: Create Clair Deployment
  k8s_apps_v1beta1_deployment:
    src: "{{ role_path }}/files/deployment.yml"
    namespace: clair