---
# tasks file for clair

# - name: Delete Clair ConfigMap
#   openshift_raw:
#     name: clair
#     namespace: clair
#     state: absent

# - name: Delete Clair Service
#   openshift_raw:
#     name: clair
#     namespace: clair
#     state: absent

# - name: Delete Clair Deployment
#   openshift_raw:
#     name: clair
#     namespace: clair
#     state: absent
