---
# Delete Objects
- name: Create Clair App Objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
    state: absent
  with_items:
  - clair-app-cm.yml.j2
  - clair-app-deployment.yml.j2
  - clair-app-service.yml.j2

- name: Delete Clair Postgres
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
    state: absent
  with_items:
  - clair-postgresql-pvc.yml.j2
  - clair-postgresql-deployment.yml.j2
  - clair-postgresql-service.yml.j2