apiVersion: v1
kind: Service
metadata:
  name: clair
  namespace: quay-enterprise
  label:
    app: clair
    component: clair-app
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: jwt-signer
spec:
  type: ClusterIP
  ports:
  - name: clair-api
    port: 6060
    targetPort: 6060
    protocol: TCP
  - name: clair-health
    port: 6061
    targetPort: 6061
    protocol: TCP
  selector:
    component: clair-app
