apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: clair
    clair-component: postgres
  name: clair-postgres
  namespace: quay-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: clair
      clair-component: postgres
  template:
    metadata:
      labels:
        app: clair
        clair-component: postgres
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
        env:
        - name: POSTGRESQL_USER
          value: clair
        - name: POSTGRESQL_PASSWORD
          value: clair
        - name: POSTGRESQL_DATABASE
          value: clair
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgres-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: clair-postgres-data
