apiVersion: v1
kind: Service
metadata:
  labels:
    app: clair
    clair-component: postgres
  name: clair-postgres
  namespace: quay-enterprise
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    clair-component: postgres
  sessionAffinity: None
  type: ClusterIP
